### ISSUE TITLE
2020-08 - roots

### ISSUE THREAD

**Issue by ultrasound1372** [thunderdrop/IBMTTSDictionaries#10]
See readme for contributing guidelines. Also I know in the last issue I just said version numbers won't have padding zeros on the month numbers, but this isn't a version number, this is a chunk of the ISO 8601 date format. Any words you wish added, propose them here.

**Comment by ultrasound1372** [comment]
I propose the following additions from the project's original root dictionary, which I am not sure of the reasoning for them not being ported by @amirsol81.
```
animorph	`[1Anxmorf]
mosen	`[m1ozXn]
thermocouple	`[T1RmokHpxl]
flowchart	`[fl1oC2art]
barchart	`[b1arC2art]
manamon	`[m1Anxman]
```
Also unsure of the proper pronunciation of sycophant.
I further propose adding italiano as a root, either as `[.0X.2ta.0li.1a.0no] or `[.0X.2tA.0li.1a.0no], not sure which pronunciation to go with. I would personally lean toward the first, but given our pronunciation of Italian things are unclear.
cc @thunderdrop

**Comment by amirsol81** [comment]
@ultrasound1372 Good points.
1. Stuff added to Root:
animorph	`[.1An.0X.2mcrf]
Quite interestingly, the Root file already contains its plural form which needs a separate correction.
mosen	`[.1mo.0zXn]
I had it in my original Root file before the merge, but have no idea why it was left out. Maybe I wanted to add it to Main but had forgotten about it.
flowchart	`[.1flo.2Cart]
barchart	`[.1bar.2Cart]
manamon	`[.1mAn.0x.2man]
Since my merge was manual, they were left out.
2. Words which need discussion:
The Root file already contains "thermocouple" and its plural form as they need two separate entries. But the correction -- based on my research -- has the following form:
`[.1TR.0mx.2kH.0pxl]
AHD 5 recommends it. What do you think?
sycophant
This word and two related terms, "sycophantic" and "sycophancy", were modified based on the recommendations made by all American dictionaries -- .1sI not .1SY although that one is also listed. But I'm open to modifications recommended here

**Comment by amirsol81** [comment]
@ultrasound1372 The archived Root also contains the following entry:
grande	`[gr1ande]
However, I haven't included it because of its conflict with the pronunciation of "grande dame":
grande dame. noun. plural.  grandes dames or also  grand dames..
1. A highly respected elderly or middle-aged woman.
2. A respected woman having extensive experience in her field: the grande dame of women's professional tennis.
3. A building or institution regarded as noteworthy on account of its age and historic prominence.

**Comment by ultrasound1372** [comment]
I wasn't referring to the sy part, I was refering to the pronunciation/stress of the phant part. It is a schwa, not a somewhat unstressed fant?

**Comment by amirsol81** [comment]
@ultrasound1372 Eloquence tends to use the .0Xnt] combination for words 
like sycophant instead of .0xnt]. Get visitant, issuant, decontaminant, 
noctivagant, triumphant, etc. So here I haven't modified that part to 
remain consistent with similar -ant-ending words.

**Comment by ultrasound1372** [comment]
Re Grande, maybe it should go in main then, it was put there because of Ariana Grande

**Comment by amirsol81** [comment]
I just added Grande, capitalized, to ENUmain.

**Comment by ultrasound1372** [comment]
I propose:
```
linearity: `[.2lI.0ni.1er.0X.0Fi]
nonlinearity: `[.2nan.2lI.0ni.1er.0X.0Fi]
```
The double secondary stress may not work, though. These are nouns which describe a system that is linear or is nonlinear. For example, the nonlinearity of the human eye's perception of brightness. I believe that using 'I' instead of 'X' is called for in this case, as the lin part should be more obvious than the default schwa would have it be.

**Comment by amirsol81** [comment]
@ultrasound1372 Agreed. I just added it to ENURoot. And nonlinearity is needed as linearity can take care of it. Quite interestingly, we already have the following entries in Root which bolster your proposal:
collinearity	`[.0kx.2lI.0ni.1Ar.0X.0Fi]

colinearity	`[.0kx.2lI.0ni.1Ar.0X.0Fi]

curvilinearity	`[.2kR.0vX.2lIn.0i.1Ar.0X.0Fi]

**Comment by ultrasound1372** [comment]
Can we do something about yeah? I'm being told by people that that's not how you say it, and I would tend to agree, but they also made fun of the sequence I was using previously, `[.1yAx]. I'm not sure which sequence would make it sound correct. Though that is probably one of the most regionally varying words so, hmmm. If all else fails we might just revert it back to the way ECI pronounces it natively.

**Comment by amirsol81** [comment]
Well, I actually removed it from ENURoot. Having disliked ECI's 
original, I tried switching to what MS SAPI 5 and MS One Core use in 
line with a couple of dictionaries, too. But the ECI original, despite 
its oddity, is also accepted by some dictionaries. The ECI issue is that 
it tends to emphasize the last schwa .0x a bit, but guess we have to 
live with it for now.

**Comment by amirsol81** [comment]
@ultrasound1372 Today is September 1st, so could you please release the monthly dictionary updates?

**Comment by amirsol81** [comment]
Guys, we have well moved past the first day of the month and the 2nd monthly dictionary update hasn't been released. May I know if this Github project has been discontinued? I want to stop posting my updates here if this is the case. Thanks.

**Comment by ultrasound1372** [comment]
Sorry. I was busy with other things and had forgotten about this, plus my computer has been really slow lately and was subject to lots of updates. Release is out now. Closing for replacement.

**Comment by amirsol81** [comment]
Thanks!
