### ISSUE TITLE
Missing license information for the project

### ISSUE THREAD

**Issue by robin24** [thunderdrop/IBMTTSDictionaries#21]
Hello,

I'm working on a project in which I may want to incorporate these wonderful dictionaries, however I am unable to find any info regarding the license under which the speech dictionaries are being provided (Creative Commons or similar).

Is there any chance to get some clarity on this, or to maybe have a License.md file included in the repo for better clarity?
Many thanks!

Cheers,
Robin

**Comment by amirsol81** [comment]
CC @ultrasound1372 @thunderdrop Would you please take a look?

**Comment by thunderdrop** [comment]
Hi Robin,

The project is presently unlicensed due to the commercial complexities of IBMTTS; we weren't even sure if we could or should license it. If pressed, I would probably say it's in the public domain. Thanks for bringing this to our attention, though, I see the value in being explicit here. So, it's community discussion time!

@ultrasound1372 and I have privately discussed some licensing options, and are thinking of potentially going the Creative Commons route. However, we'd like some input from @amirsol81, without whom this project wouldn't be remotely what it is today. Amir, as the person who has demonstrably put the most time and effort into these dictionaries, how do you feel about attribution? It's my thinking that none of us hold any copyright to this work, and my preference that we don't claim any. However, if you would prefer that your work here, both prior to and during the life of this project, does not go unrecognized, we can find a solution for that.

**Comment by amirsol81** [comment]
@thunderdrop Thanks for the explanation. I also think that I don't hold any copyright to this dictionary work, so feel free to do whatever is appropriate.

**Comment by robin24** [comment]
Hey all,

I just wanted to thank you for the super fast response and your thoughtful considerations, happy to see my inquiry has sparked such a productive discussion 👍.

Personally speaking I'd love to see this officially getting a Creative Commons license, as I think it allows for the most freedom and flexibility both for those of you maintaining the project and people like me wanting to use the material.

Cheers, looking forward to the final decision!
Robin

**Comment by amirsol81** [comment]
@thunderdrop @ultrasound1372 Now that November's release of the dictionaries is to be made available shortly, any chance of taking care of the Creative Commons license? I also suggest removing the "Archived" folder altogether as it has been totally incorporated into the project.
