### ISSUE TITLE
2023-09 - roots

### ISSUE THREAD

**Issue by ultrasound1372** [thunderdrop/IBMTTSDictionaries#42]
See readme for contributing guidelines.

**Comment by nicopn** [comment]
Requests:
```
hashmap	`[.1hAS.2mAp]
zipbomb	`[.1zIp.2bam]
putchar	`[.1pUt.2Car]
charmap	`[.1Car.2mAp]
reverb	`[.1ri.2vRb]
raum	`[.1rWm]
voldemort	`[.1vol.0dx.2mcrt]
imovie	`[.1Y.2mu.0vi]
```
Notes:
* For some reason, "voldemort" had a missing t in its SPR all this time.
* Though \`[.0rX.1vRb] is what most dictionaries agree is correct, I've heard \`[.1ri.2vRb] be more common.
* Raum (pronounced roum according to Native Instruments themselves) is a reverb plugin made by Native Instruments.

Also, I suggest reverting "exe" and "txt" to be spelled out (again because commonality) and have "ini" also be spelled out. "Wav" may need discussion, since both "wahv" and "wave" are quite commonly heard.

**Comment by amirsol81** [comment]
@nicopn Thanks - all valid suggestions! I just made the needed changes to Root/Main with the latest commit, and modified "voldemort" and "reverb" as well. Ini/exe/wav have also been removed.

**Comment by nicopn** [comment]
Thanks for the commit! I think that "exe" should be spelled out (E X E) as it was before it got changed to sound like "exy". Other than that, it's great!

**Comment by amirsol81** [comment]
@nicopn Sure, it was just done with the return of exe	ee eks ee to main with a new commit.

**Comment by ultrasound1372** [comment]
The pronunciation of reverb is contested I guess, I think depending on whether it's a noun or not. I do prefer that voldemort has a t, though, and have had this in my personal branch for some time. Just ensure that your entry for reverb doesn't break reverberate and variants.

**Comment by amirsol81** [comment]
@ultrasound1372 Quite interestingly, only dictionary.com says that "reverb" can be used as a verb with stress on the "verb" syllable. But Merriam-Webster and Oxford Dictionary only mention its noun usage which primarily receives stress on the first syllable. The modification doesn't break words but I'm now adding a few related words, too.

**Comment by ultrasound1372** [comment]
Closing as we've transitioned to the next month and discussion here has concluded, will open a fresh issue.
